### ISSUE TITLE
No valid credentials found with log drainer setting

### ISSUE THREAD

**Issue by priyabubbles** [philips-software/fluent-bit-out-hsdp#100]
We tried to configure the log drainer url to aggregate the logs, but when we try to run the command for build, we are getting "no valid credentials found".

we used the below settings:

docker run --rm \
    -p 127.0.0.1:24224:24224 \
    -e HSDP_LOGDRAIN_URL=https://logdrainer-xxxx-healthsuite.com/core/log/Product/xxxxx \
    -it philipssoftware/fluent-bit-out-hsdp:latest

**Comment by loafoe** [comment]
@priyabubbles please try with image `philipssoftware/fluent-bit-out-hsdp:1.9.5.0` -- looks like `latest` is actually not the latest. Will look into that

**Comment by loafoe** [comment]
`latest` tag was fixed

**Comment by priyabubbles** [comment]
Thanks Andy !
