### ISSUE TITLE
InsecureSkipVerify and Debug variables

### ISSUE THREAD

**Issue by khhipparagi** [philips-software/fluent-bit-out-hsdp#40]
The current code checks for these variables either present or not. Based on that the action is taken care. However it would be nice, if code checks for boolean value, e.g. Debug=true then set else disable. Similarly for InsecureSkipVerify. 
As we want to expose these variables in docker-compose so client can decide.

The default values for both can be false.

**Comment by loafoe** [comment]
@khhipparagi this is correct. I will look into adding proper "boolean" check, where only "true" would accept
