### ISSUE TITLE
Not able to generate new token for service identity after 30 minute expiry

### ISSUE THREAD

**Issue by ajinkya-ghatol** [philips-software/fluent-bit-out-hsdp#45]
Hi Andy,
I tested fluent bit plugin by providing service identity details. It works as expected for first 30 minutes. But after that it get stuck somewhere while getting token for service identity, there are no logs to console.
Looks like it’s not able to get new token for service identity after expiry.

**Comment by loafoe** [comment]
hi @ajinkya-ghatol , issue was fixed here: https://github.com/philips-software/go-hsdp-api/commit/6de4e0e1021a225dd1290bde9a5b031e2eb725e4 . Please try the `1.8.9.0` release.

**Comment by loafoe** [comment]
confirmed to work by @ajinkya-ghatol 🎆
