### ISSUE TITLE
Support for log-drainer capabilities as similar to CF bind service

### ISSUE THREAD

**Issue by git-sudarshan** [philips-software/fluent-bit-out-hsdp#56]
In CF we were just binding deployed apps with the log drainer service (cups service to the HSP log host URL),
But now through fluent-bit-out-hsdp plugin and log ingestor approach we are forced to provide service identity detail or shared & secret key pair.

With logdrainer I mean, instead of using service identity or shared key/secrey, we would simply provide the logdrainer URL only as config.

**Comment by loafoe** [comment]
@git-sudarshan Implemented in version `1.9.2.x` and above
